debugging: false
send-anonymous-statistics: true
automatic-updates:
  enabled: true
  method: automatic
  branch: stable
surpress-list-name-too-long-warning: false
colour-messages:
  death: true
  join: true
  list: true
  quit: true
